# Generated by Django 5.2.6 on 2025-09-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_specialization_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='specialization_name',
        ),
    ]
