# Generated by Django 5.2.6 on 2025-09-07 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_office_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.CharField(verbose_name='Номер кабинета'),
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('status', models.BooleanField(verbose_name='Статус посещения')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.office')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.teacher')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещение',
            },
        ),
    ]
