# Generated by Django 5.2.6 on 2025-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_office_number_visiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiting',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время посещения'),
        ),
    ]
